#!/bin/sh

# For Unix users only !
# Make sure SWI-Prolog.app is in the /Applications directory
# Add the line below in your .bash_profile (in the root directory)
# export PATH=/Applications/SWI-Prolog.app/Contents/MacOS:$PATH

swipl -s puissance.pl