#!/bin/sh

# For Mac users only !
# Make sure SWI-Prolog.app is in the /Applications directory

export PATH=/Applications/SWI-Prolog.app/Contents/MacOS:$PATH
clear
clear
swipl -s puissance.pl -t "puissanceAuto" 